swagger: "2.0"
info:
  description: "File server documentation"
  version: "1.0.0"
  title: "File server"
  license:
    name: "WTFPL"
host: "127.0.0.1:8081"
basePath: "/v1/api"
schemes:
- "http"
paths:
  /upload:
    post:
      summary: "Upload a file to the server"
      description: ""
      operationId: "uploadFile"
      consumes:
      - "multipart/form-data"
      produces:
      - "application/json"
      parameters:
      - name: "file"
        in: "formData"
        description: "File to upload"
        required: true
        type: "string"
      responses:
        200:
          description: "Successfull operation"
          schema:
            $ref: "#/definitions/UploadFileHandlerSuccessResponse"
        400:
          description: "Either no file were selected to upload or max files size was exceeded. See UploadFileHandlerFailResponse.code for more information"
          schema:
            $ref: "#/definitions/UploadFileHandlerFailResponse"
        500:
          description: "Unknown server error"
          schema:
            $ref: "#/definitions/UploadFileHandlerFailResponse"
  /download/{file_name}:
    get:
      summary: "Download a file from the server"
      description: ""
      operationId: "downloadFile"
      consumes:
      - "application/json"
      produces:
      - "application/octet-stream"
      parameters:
      - name: "file_name"
        in: "path"
        description: "The name of the file to be downloaded"
        required: true
        type: "string"
      responses:
        200:
          description: "Successfull operation"
        404:
          description: "File was not found"
          schema:
            $ref: "#/definitions/BaseServerResponse"
        500:
          description: "Unknown server error"
          schema:
            $ref: "#/definitions/BaseServerResponse"

definitions:
  UploadFileHandlerSuccessResponse:
    type: "object"
    properties:
      uploaded_file_name:
        type: "string"
      code:
        type: "integer"
        format: "int32"
        description: "Server Response Code"
        enum:
        - "Unknown Error"
        - "Ok"
        - "No File To Upload"
        - "Max file size exceeded"

  UploadFileHandlerFailResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
        description: "Server Response Code"
        enum:
        - "Unknown Error"
        - "Ok"
        - "No File To Upload"
        - "Max file size exceeded"
      message:
        type: "string"

  BaseServerResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
        description: "Server Response Code"
        enum:
        - "Unknown Error"
        - "Ok"
        - "No File To Upload"
        - "Max file size exceeded"
      message:
        type: "string"
































    
